### ISSUE TITLE
It does not look at, in Ubuntu 20.04

### ISSUE THREAD

**Issue by lwbaqueros** [lifeofcoding/ulauncher-youtube#6]
When I am trying to fetch it does not show any content. Please tell me what kind of additional info you would need to know the source of this problem.

1. Ubuntu 20.04.1 Fresh installation.
![Uploading Screenshot from 2020-09-06 23-53-34.png…](It gets stuck in loading, and then it disappears.)

**Comment by lwbaqueros** [comment]
![Screenshot from 2020-09-06 23-53-34](https://user-images.githubusercontent.com/46763074/92335978-5764a700-f09c-11ea-816f-4c70c66e5f0f.png)

**Comment by TheZuna** [comment]
Same problem, debian.

**Comment by norbr9** [comment]
Since this project seems abandoned, I have created a new extension that actually works. You can find it on https://github.com/norbr9/ulauncher-youtube-search

**Comment by lwbaqueros** [comment]
@norbr9  super. It works find in Ubuntu 20.04. thanks for that

**Comment by lwbaqueros** [comment]
![youtube](https://user-images.githubusercontent.com/46763074/94336705-5365de00-ffe5-11ea-95f8-75fc68038766.png)
